CUDA_VISIBLE_DEVICES='0' OMP_NUM_THREADS=1 python -m torch.distributed.launch --nproc_per_node=1 main_finetune.py \
    --data_path '/home/hlsheng/mae_data/finetune/CO2/' \
    --task 'CO2' \
    --accum_iter 1 \
    --batch_size 90 \
    --input_size 192 \
    --model vit_large_patch16 \
    --modelComparsion 'Deeplab' \
    --output_dir './finetune_result/CO2/Deeplab/' \
    --log_dir './finetune_result/CO2/Deeplab/' \
    --epochs 100 \
    --warmup_epochs 10 \
    --blr 1.5e-3 --weight_decay 0.05 \
    --layer_decay 0.05 --drop_path 0.1 --reprob 0.25 \
    --dist_eval
